Feat/button refactor
rei/rei-cedar-vue-2 pull request #415
Opened 2018-04-30 15:32 UTC by darintrimillos

Figured I could get some PR comments while I'm out of office...

2018-04-30 15:59 UTC, lancetharper requested changes
Make sure you are PRing to `cedar2` instead of `master` since we aren't on that yet! :D

2018-05-15 16:18 UTC, darintrimillos commented
I still need to add more tests and documentation, but I think this can start to be reviewed now. I'm still playing with some styling details, but I doubt that'll turn into significant code changes. Removed Kevin as a reviewer as he is OOO.

2018-05-18 20:54 UTC, lancetharper commented on src/components/button/styles/CdrButton.pcss
> +    &--small\@extra-small {
We need to decide if breakpoints in class names are full or t-shirt (extra-small vs xs). Grid does t-shirt and is the only other place that has had this so far. Thoughts @mhewson ?

2018-05-18 20:54 UTC, lancetharper commented on src/components/cta/styles/CdrCta.pcss
> +  & > .cdr-icon {
Does this needed to be updated to `.cdr-cta__icon` or whatever?

2018-05-23 20:34 UTC, mhewson commented on src/components/button/CdrButton.vue
> + * CdrButton will render either a button, or an anchor that looks like a button.
this should be removed from the component doc 
-- review list for readme formatting -- https://docs.google.com/document/d/1AsWyydyKs91GFrHUiDBMUgWVXK5jFnEqK0Wu8ljyDiI/edit
https://github.com/rei/rei-cedar/tree/cedar2/src/components/list

@SoundtrkSamurai what comment structure should exist within components now for the proposed automated api?

2018-05-23 23:43 UTC, darintrimillos commented on src/components/button/CdrButton.vue
> + * CdrButton will render either a button, or an anchor that looks like a button.
Left this comment in since it won't get pulled into the docs site. Updated readmes to match guidelines better.

2018-05-25 16:40 UTC, lancetharper requested changes

2018-05-25 16:40 UTC, lancetharper commented on src/components/cta/styles/CdrCta.pcss
> +  & > .cdr-button__icon {
Mixing `.cdr-button` and `.cdr-cta` base classes might cause problems once we're on css-modules. I'd recommend just sticking with `.cdr-cta` everywhere.

2018-05-25 17:18 UTC, mhewson commented on src/components/button/examples/demo/Default.vue
>        <cdr-button
looks like there my be a display bug on this variant moving into the small breakpoint  - what I am seeing is that it collapses to its default width rather than full prior to shifting down sizes and snapping back to full width

2018-05-25 17:20 UTC, mhewson commented on src/components/button/CdrButton.backstop.js
> +      '[data-backstop="cdr-button--large"]',
was there work to do to reduce the overall amount of visual regression testing here?

2018-05-25 17:29 UTC, lancetharper commented on src/components/button/CdrButton.backstop.js
> +      '[data-backstop="cdr-button--large"]',
Yes, are you on the latest? I cleaned up all of the backstop tests

2018-05-25 17:29 UTC, lancetharper approved these changes

2018-05-25 17:49 UTC, darintrimillos commented on src/components/button/examples/demo/Default.vue
>        <cdr-button
This looks correct to me. If going from large to small, it will start full width. Then at the sm breakpoint it becomes a large button, and if you keep going at xs it becomes full width again.

2018-05-25 17:54 UTC, mhewson commented on src/components/button/examples/demo/Icons.vue
> +      <cdr-button
Please ensure our examples are passing accessibility- icon only examples should have screenreader text  -

2018-05-25 18:25 UTC, darintrimillos commented on src/components/button/examples/demo/Icons.vue
> +      <cdr-button
These updates were done a couple of days ago. Not sure why it's not showing for you in Github, but I see them in the code. https://github.com/rei/rei-cedar/blob/feat/button-refactor/src/components/iconOnlyButton/examples/IconOnlyButton.vue

2018-05-26 01:41 UTC, merged