feat(icon): bump version, update README
rei/rei-cedar-vue-2 pull request #534
Opened 2018-12-05 20:03 UTC by darintrimillos

affects: @rei/cdr-icon

BREAKING CHANGE:
size values go to size prop rather than modifier prop

2018-12-05 20:17 UTC, mhewson requested changes

2018-12-05 20:17 UTC, mhewson commented on src/components/icon/README.md
> +| Modifiers the icon size; values can target responsive breakpoints. Breakpoint values are: xs, sm, md, and lg. Examples: { 'small' | 'medium' | 'large' | 'large@sm' }  |        |         |
do you mean Modifies the icon size?

2018-12-06 18:37 UTC, lancetharper approved these changes
🎉

2018-12-06 19:49 UTC, mhewson approved these changes

2018-12-06 19:52 UTC, merged