Feat/select input consistency
rei/rei-cedar-vue-2 pull request #686
Opened 2019-09-27 18:07 UTC by KrisKnabel

To view this build go to: http://rei-cedar-components-demo.s3-website-us-west-2.amazonaws.com/#/selects

Known Issues:

Firefox: 
  - Dotted outline does not match up to border
  - Prompt styling affects options before selection is made, then is normal

Internet Exporer/Edge
  - Same prompt styling issue as Firefox
  - V-Model not updating selection(Fixing this now)

2019-09-27 20:06 UTC, KrisKnabel commented
Fixed IE v-model issue.

2019-09-27 20:22 UTC, KrisKnabel commented
Fixed Linter space complaint.  This should be ready for review.

2019-09-27 20:47 UTC, lancetharper commented on src/components/select/styles/vars/CdrSelect.vars.scss
> +// $cdr-select-base-font-size: 16px;
Is there any reason to keep all of this commented out stuff?

2019-09-27 20:53 UTC, lancetharper requested changes

2019-09-27 20:53 UTC, lancetharper commented on src/components/select/CdrSelect.jsx
> +              vm.$emit('input', selected);
missing emitting the event in a couple places (and unit tests for these new events)

2019-09-27 21:30 UTC, KrisKnabel commented on src/components/select/styles/vars/CdrSelect.vars.scss
> +// $cdr-select-base-font-size: 16px;
Not anymore, I will remove these comments.

2019-09-27 21:34 UTC, KrisKnabel commented on src/components/select/CdrSelect.jsx
> +              vm.$emit('input', selected);
Good callout on the missing unit tests.  I will add some.

2019-09-27 21:34 UTC, KrisKnabel commented on src/components/select/CdrSelect.jsx
> +              vm.$emit('input', selected);
What places do you think the event emitting is missing?

2019-09-27 22:01 UTC, lancetharper commented on src/components/select/CdrSelect.jsx
> +              vm.$emit('change', selected, event);
@KrisKnabel Like here. Emit the `value` (selected), and the `event`

2019-09-30 14:49 UTC, KrisKnabel commented on src/components/select/CdrSelect.jsx
> +              vm.$emit('input', selected);
I think what you are asking is to pass through the event object.  I looked at how Cole refactored the Input component, and she did not attach the event object.  I then looked at the Vue docs: https://vuejs.org/v2/guide/components-custom-events.html  they also don't attach the event object.  I guess adding the original event object won't hurt and could be useful.

2019-09-30 14:59 UTC, KrisKnabel commented on src/components/select/CdrSelect.jsx
> +              vm.$emit('change', selected, event);
Attached original event object

2019-09-30 15:29 UTC, lancetharper commented on src/components/select/CdrSelect.jsx
> +              vm.$emit('input', selected);
Yeah it's probably not a big deal, I just think we're just better off having it in there now rather than someone discovering they need/want it later and us having to make an update (or push it to the next release)

2019-09-30 15:30 UTC, lancetharper commented on src/components/select/CdrSelect.jsx
> +              vm.$emit('change', selected, event);
Sweet, don't forget to update the emitted events docs to include it! 👍

2019-09-30 15:31 UTC, lancetharper approved these changes

2019-09-30 15:32 UTC, merged