fix(select): fix caret icon to show disabled styling
rei/rei-cedar-vue-2 pull request #693
Opened 2019-10-11 17:44 UTC by KrisKnabel

Caret icon is not showing disabled, this change fixes the caret icon to display properly when
disabled.  Pointed out by the Cedar Designers and they requested the fix.

2019-10-11 19:04 UTC, lancetharper submitted a review, later dismissed

2019-10-11 19:10 UTC, cowills requested changes

2019-10-11 19:10 UTC, cowills commented on src/components/select/styles/vars/CdrSelect.vars.scss
> +  fill: $cdr-color-icon-primary-lightmode;
you need to create variables for all these properties if you're going to map these like this. It's fine to just leave this CSS un-mapped instead.

2019-10-14 16:50 UTC, KrisKnabel commented on src/components/select/styles/vars/CdrSelect.vars.scss
> +  fill: $cdr-color-icon-primary-lightmode;
When you say variables, are you referring to Cedar Component Variables?

2019-10-14 17:07 UTC, cowills commented on src/components/select/styles/vars/CdrSelect.vars.scss
> +  fill: $cdr-color-icon-primary-lightmode;
the `vars.scss` files are the component variables. if you aren't going to map each of these values to a variable then you should just keep these changes in the main scss file for select

2019-10-14 17:21 UTC, KrisKnabel commented on src/components/select/styles/vars/CdrSelect.vars.scss
> +  fill: $cdr-color-icon-primary-lightmode;
I see what you mean now.  Sorry for the confusion.  I was looking at the code above the comment, not below, and wondering if you were referring to running `npm run build:variables`.

2019-10-14 23:22 UTC, KrisKnabel commented on src/components/select/styles/vars/CdrSelect.vars.scss
> +  fill: $cdr-color-icon-primary-lightmode;
Updated the select caret style properties to map to SCSS variables.

2019-10-14 23:22 UTC, KrisKnabel commented
Added Unit Test to cover Cedar Select Caret Disabled state.

2019-10-15 21:25 UTC, closed without merging

2019-10-15 21:26 UTC, KrisKnabel commented
Closing as PR 696 resolves the need for this.